"use client";
// 브라우저에서 구성 요소를 렌더링하도록 지시

import "./globals.css";
import { theme } from "./theme/themes";
import Image from "next/image";
import { ThemeProvider, CssBaseline, Switch, FormControlLabel, styled, Box, Typography } from "@mui/material";

import Header from "./component/Header";
import Footer from "./component/Footer";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
        <body id="__next">
          <CssBaseline />
          {/* <FormControlLabel
            control={
              <Switch
                checked={useDarkTheme}
                inputProps={{ "aria-label": "Dark Mode" }}
                onChange={(target, value) => changeThemeHandler(target, value)}
              ></Switch>
            }
            label="Dark Mode"
            labelPlacement="start"
          /> */}
          <Banner>
            <Typography variant="h4">기업 학교 고객이신가요?</Typography>
            <Typography variant="h4">
              쉐이킷 B2B 전용몰
              <Image src="/arrow_pink.svg" alt="arrow" width={9} height={9} />
            </Typography>
          </Banner>
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
const Banner = styled(Box)(({ theme }) => ({
  display: "flex",
  justifyContent: "center",
  padding: "14px 0",
  background: theme.palette.background.paper,
  h4: {
    color: "#000",
  },
  "h4 + h4": {
    display: "flex",
    alignItems: "center",
    color: theme.palette.primary.main,
    fontWeight: 700,
    marginLeft: "8px",
    img: {
      marginLeft: "17px",
    },
  },
}));
